### ISSUE TITLE
FullStack JavaScrip Track Courses To Be Completed

### ISSUE THREAD

**Issue by devcamletswork** [devcamletswork/Treehouse#1]
## TODO

*Courses left to complete the Full-Stack JavaScript Track*

- [ ] STRUCTURING JS CODE
- [ ] CSS SELECTORS 
- [ ] Open a pull request
- [ ]  AJAX BASICS
- [ ] ASYNCHRONOUS PROGRAMMING WITH JS
- [ ] WORKING WITH THE FETCH API
- [ ] OO JS
- [ ] OO JS-CHALLENGE
- [ ] NODE JS
- [ ] JS CONDITIONALS
- [ ] BUILD DYNAMIC SITE WITH NODE.JS
- [ ] NPM BASICS 
- [ ] USING NPM AS A TASK RUNNER
- [ ] EXPRESS BASICS
- [ ] UNDERSTANDING CLOSURES IN JS
- [ ] DEBUG NODE APPS WITH VS CODE
- [ ] ASYNCHRONOUS CODE IN EXPRESS
- [ ] REST APIS WITH EXPRESS
- [ ] SQL BASICS
- [ ] MODIFYING DATA WITH SQL
- [ ] USING SQL ORMS WITH NODE.JS
- [ ] USING SEQUELIZE ORM WITH EXPRESS 

## UNIT 2  TECH DEGREE COURSE ORDER

- [ ] Css selectors	
- [ ] Structuring js code	
- [ ] Js and the dom	
- [ ] Dom scripting by example
- [ ] Debugging js in browser
- [ ] Plan ahead with pseudocode 
- [ ] Translating pscode to js

## UNIT 3 TECH DEGREE COURSE ORDER
- [ ] Landscape of js
- [ ] Html forms
- [ ] Accessibility for web devs
- [ ] Js conditionals
- [ ] Sting manipulating with js
- [ ] Regular expressions in js

## UNIT 4TECH DEGREE COURSE ORDER
- [ ] OO JavaScript
- [ ] Callback functions in js
- [ ] Js array iteration methods

## UNIT 5TECH DEGREE COURSE ORDER
- [ ] Api requests
- [ ] Http basics
- [ ] Ajax basics
- [ ] synchronous programming with javascript
- [ ] Fetch api
